apiVersion: v1
kind: Service
metadata:
  name: python-app-public
  namespace: day02-networking
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
    - name: http
      port: 8089
      targetPort: 8000
