#!/usr/bin/env bash
# Stage12-GitHub G3: same pattern as Stage09's create-redis-secret.sh, for
# the capstone-github namespace. The chart references existingSecret:
# redis-auth and never generates a password itself (Stage11's chart
# comment: "created ONCE, outside this chart, never regenerated by an
# upgrade" - same reasoning applies to this second copy).
set -euo pipefail
NS=capstone-github

if ! kubectl get namespace "$NS" >/dev/null 2>&1; then
  kubectl create namespace "$NS"
fi

if kubectl -n "$NS" get secret redis-auth >/dev/null 2>&1; then
  echo "secret/redis-auth already exists in $NS - kept"
  exit 0
fi

kubectl -n "$NS" create secret generic redis-auth \
  --from-literal=password="$(openssl rand -hex 24)"
kubectl -n "$NS" label secret redis-auth app.kubernetes.io/part-of=capstone
